### ISSUE TITLE
'USER STORY: Authentication

### ISSUE THREAD

**Issue by Hasmelash95** [folarin-ogungbemi/Femtoring#15]
As a **Admin/User** I can **Sign in/Sign up** so that I can **get access to features of the website I otherwise couldn't.**

Acceptance Criteria: Use Django authentication system to allow users to Sign in/Sign Up or Logout. Customise the pages.

Tasks:

- [x] Create a superuser account that all collaborators can access. 
- [x] Add an accounts url so authentication pages can be accessed from the nav.
- [x] Create sign in/sign up/logout templates that can be customised.

**Comment by folarin-ogungbemi** [comment]
All task completed
